name: "The United States Web Design System (USWDS) 2.0 Hugo Theme NIST Customization"
license: "CCO"
licenselink: "https://github.com/usnistgov/hugo-uswds/blob/master/LICENSE.md"
description: "A hugo theme based on the United States Web Design System (USWDS) 2.0"
homepage: "https://github.com/usnistgov/hugo-uswds"
tags:
features:
min_version: "0.111.0"
author:
  name: "David Waltermire"
  homepage: "https://www.nist.gov/people/david-waltermire"
module:
  hugoVersion:
    min: 0.111.0
    extended: true
  mounts:
  - source: layouts
    target: layouts
  - source: static/css
    target: static/module/hugo-uswds-nist/css
  imports:
  - path: github.com/usnistgov/hugo-uswds
#  replacements: |
#    github.com/usnistgov/hugo-uswds -> ../hugo-uswds
